# Generated by Django 2.1.3 on 2018-11-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('farmer', models.CharField(max_length=255)),
                ('kilograms', models.CharField(max_length=255)),
                ('rate', models.CharField(default=35, max_length=255)),
                ('amount', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_salary', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('bank', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=0)),
                ('membership_number', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('bank', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='FarmerAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=255)),
                ('total_delivery_days', models.CharField(max_length=255)),
                ('total_kilograms', models.CharField(max_length=255)),
                ('total_pay', models.CharField(max_length=255)),
                ('average_monthly_kilograms', models.CharField(max_length=255)),
                ('average_monthly_pay', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Monthly_total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=255)),
                ('farmer', models.CharField(max_length=255)),
                ('total_kilograms', models.CharField(max_length=255)),
                ('rate', models.CharField(default=35, max_length=255)),
                ('total_amount', models.CharField(max_length=255)),
                ('vet_loans', models.CharField(blank=True, max_length=255, null=True)),
                ('advance', models.CharField(blank=True, max_length=255, null=True)),
                ('store_loans', models.CharField(blank=True, max_length=255, null=True)),
                ('total_loans', models.CharField(blank=True, max_length=255, null=True)),
                ('total_deductions', models.CharField(blank=True, max_length=255, null=True)),
                ('net_pay', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_balance', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyBusinessReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=255)),
                ('total_payments', models.CharField(max_length=255)),
                ('total_salaries', models.CharField(max_length=255)),
                ('total_expenditure', models.CharField(max_length=255)),
                ('profit_or_loss', models.CharField(max_length=255)),
            ],
        ),
    ]
