# Generated by Django 2.1.3 on 2018-11-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monthly_total',
            new_name='MonthlyTotal',
        ),
    ]
